import type { Metadata } from "next";
import { Prompt } from "next/font/google";
import "./globals.css";
import { NavigationMenuNavBar } from "@/components/layouts/navbar";

const prompt = Prompt({
  variable: "--font-prompt",
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Warehouse Next Application",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${prompt.variable} antialiased`}>
        <NavigationMenuNavBar />
        {children}
      </body>
    </html>
  );
}
